name: gha-basic-building-block-ass-workflow2
on: [issues, workflow_dispatch]
jobs:
  report-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Report issue
        run: echo "${{ toJSON(github) }}"
